//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBS_BTL
{
    public partial class DangKy
    {
        /// <summary>
        /// divThongBao control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divThongBao;

        /// <summary>
        /// litThongBao control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litThongBao;

        /// <summary>
        /// txtHoTen control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHoTen;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtSoDienThoai control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSoDienThoai;

        /// <summary>
        /// txtMatKhau control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMatKhau;

        /// <summary>
        /// txtNhapLaiMatKhau control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNhapLaiMatKhau;

        /// <summary>
        /// btnDangKy control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDangKy;

        /// <summary>
        /// lnkToDangNhap control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkToDangNhap;
    }
}
