//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBS_BTL
{
    public partial class DanhSachSp
    {
        protected global::System.Web.UI.WebControls.Label lblTieuDe;
        protected global::System.Web.UI.WebControls.Label lblSoLuong;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptSach;
        protected global::System.Web.UI.WebControls.Panel pnlPagination;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkPrev;
        protected global::System.Web.UI.WebControls.Label lblPage;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkNext;
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;
        protected global::System.Web.UI.WebControls.CheckBoxList cblTheLoai;
        protected global::System.Web.UI.WebControls.CheckBoxList cblGia;
        protected global::System.Web.UI.WebControls.CheckBoxList cblKho;
        protected global::System.Web.UI.WebControls.Button btnApDungLoc;
        protected global::System.Web.UI.WebControls.Panel activeFilters;
        protected global::System.Web.UI.WebControls.Repeater rptActiveFilters;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkResetFilters;
    }
}
