//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBS_BTL
{
    public partial class ChiTietKhachHang
    {
        protected global::System.Web.UI.HtmlControls.HtmlImage imgAvatar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblHoTen;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblEmail;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblSoDienThoai;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblGioiTinh;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblNgaySinh;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTrangThai;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblNgayDangKy;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblLanDangNhapCuoi;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblHangThanhVien;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDiaChiMacDinh;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDiaChiKhac;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlDiaChiKhac;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTongDonHang;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTongChiTieu;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDonThanhCong;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDonHuy;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlDonHangList;
        protected global::System.Web.UI.WebControls.Repeater rptDonHang;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlNoOrders;
        protected global::System.Web.UI.WebControls.Button btnKhoaTaiKhoan;
        protected global::System.Web.UI.WebControls.Button btnMoKhoaTaiKhoan;
        protected global::System.Web.UI.WebControls.Button btnDatLaiMatKhau;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlActionMessage;
        protected global::System.Web.UI.WebControls.Literal litActionMessage;
    }
}
