//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBS_BTL
{
    public partial class QuanLy
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm formAdmin;

        protected global::System.Web.UI.WebControls.LinkButton lnkTabSach;
        protected global::System.Web.UI.WebControls.LinkButton lnkTabDonHang;
        protected global::System.Web.UI.WebControls.LinkButton lnkThoat;

        protected global::System.Web.UI.WebControls.Label lblAdminInfo;
        protected global::System.Web.UI.WebControls.Panel pnlTabSach;
        protected global::System.Web.UI.WebControls.Label lblBookCount;
        protected global::System.Web.UI.WebControls.Panel pnlBookEditor;
        protected global::System.Web.UI.WebControls.Button btnCloseInlineEditor;
        protected global::System.Web.UI.WebControls.Button btnThemSach;
        protected global::System.Web.UI.WebControls.GridView gvSach;

        protected global::System.Web.UI.WebControls.TextBox txtMaSach;
        protected global::System.Web.UI.WebControls.TextBox txtTenSach;
        protected global::System.Web.UI.WebControls.TextBox txtTacGia;
        protected global::System.Web.UI.WebControls.TextBox txtNxb;
        protected global::System.Web.UI.WebControls.TextBox txtGia;
        protected global::System.Web.UI.WebControls.TextBox txtSoTrang;
        protected global::System.Web.UI.WebControls.DropDownList ddlTinhTrang;
        protected global::System.Web.UI.WebControls.TextBox txtTheLoai;
        protected global::System.Web.UI.WebControls.TextBox txtMoTa;

        protected global::System.Web.UI.WebControls.FileUpload fuAnhBia;
        protected global::System.Web.UI.WebControls.HiddenField hfAnhCu;

        protected global::System.Web.UI.WebControls.FileUpload fuAnh1;
        protected global::System.Web.UI.WebControls.FileUpload fuAnh2;
        protected global::System.Web.UI.WebControls.FileUpload fuAnh3;
        protected global::System.Web.UI.WebControls.FileUpload fuAnh4;
        protected global::System.Web.UI.WebControls.HiddenField hfAnhMinhHoaCu;
        protected global::System.Web.UI.WebControls.HiddenField hfAnhMinhHoaUrl;

        protected global::System.Web.UI.WebControls.Button btnLuuSach;

        protected global::System.Web.UI.WebControls.Panel pnlTabDonHang;
        protected global::System.Web.UI.WebControls.Label lblOrderCount;
        protected global::System.Web.UI.WebControls.GridView gvDonHang;

        protected global::System.Web.UI.WebControls.LinkButton lnkTabKhachHang;
        protected global::System.Web.UI.WebControls.Panel pnlTabKhachHang;
        protected global::System.Web.UI.WebControls.Label lblKhachHangCount;
        protected global::System.Web.UI.WebControls.GridView gvKhachHang;
    }
}
